local pawnShopItems = {
    { item = "Wristwatch", price = 50.00 },
    { item = "Gold Ring", price = 120.00 },
    { item = "Silver Necklace", price = 80.00 },
    { item = "Pocket Knife", price = 25.00 },
    { item = "Smartphone", price = 200.00 },
    { item = "Bluetooth Speaker", price = 45.00 },
    { item = "Digital Camera", price = 150.00 },
    { item = "Tablet", price = 180.00 },
    { item = "Laptop Charger", price = 20.00 },
    { item = "Headphones", price = 35.00 },
    { item = "Video Game Controller", price = 30.00 },
    { item = "Portable Hard Drive", price = 60.00 },
    { item = "Smartwatch", price = 120.00 },
    { item = "Handheld Game Console", price = 100.00 },
    { item = "Fitness Tracker", price = 70.00 },
    { item = "Electric Shaver", price = 40.00 },
    { item = "Wallet", price = 15.00 },
    { item = "Sunglasses", price = 25.00 },
    { item = "Perfume", price = 50.00 },
    { item = "Designer Belt", price = 75.00 },
    { item = "External Battery Pack", price = 25.00 },
    { item = "Memory Card", price = 10.00 },
    { item = "Portable Speaker", price = 35.00 },
    { item = "Action Camera", price = 90.00 },
    { item = "Mini Projector", price = 100.00 },
    { item = "Binoculars", price = 60.00 },
    { item = "Electric Toothbrush", price = 30.00 },
    { item = "Compact Mirror", price = 5.00 },
    { item = "Flashlight", price = 15.00 },
    { item = "Wireless Earbuds", price = 50.00 },
    -- Adding rarer and more expensive items
    { item = "Vintage Rolex Watch", price = 5000.00 },
    { item = "Antique Gold Coin", price = 2000.00 },
    { item = "Diamond Necklace", price = 7000.00 },
    { item = "Limited Edition Designer Handbag", price = 2500.00 },
    { item = "Rare Vintage Guitar", price = 3000.00 }
}

